site_name: omicverse-reproducibility
repo_url: https://github.com/Starlitnightly/omicverse-reproducibility
site_author: "Zehua Zeng"
copyright: "Copyright &copy; 2019-2023, 112 Lab, USTB"


nav:
- Home: 'index.md'
- Supplement bulk2single: 'ov_bulk2single_ad.ipynb'
- Supplement DEG: 'ov_deg.ipynb'
- Supplement WGCNA: 'ov_wgcna.ipynb'
- Supplement GLUE prepare: 'ov_glue_preprocessed.ipynb'
- Supplement MOFA : 'ov_mofa.ipynb'

  


plugins:
  - mkdocs-jupyter
  - glightbox
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/ico.png
  favicon: img/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/custom.css